"=========== Vimrc ===========

runtime! parabola.vim " *** See message at bottom
set nocompatible " use vim settings not vi 

" ----- plugin file -----
source ~/.vim/plugins.vim

" ----- swap file -----
set directory=~/.vim/.swaps//

"======== Keybindings ======
" leader key - comma
let mapleader = ','

" On honeysuckle:
" <esc> key mapped to <CapsLock> in X using this command: xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

inoremap <leader><tab> <esc> " Escape
inoremap <leader>a <esc> " Escape

" Edit vimrc in new window, horizontal split
nmap <leader>vv :e! ~/.dotfiles/vim/vimrc<cr>
nmap <leader>vs :sp! ~/.dotfiles/vim/vimrc<cr>
nmap <leader>l :so ~/.vimrc<cr>

nnoremap gj j
nnoremap gk k
nnoremap j gj
nnoremap k gk

" Insert blank lines below or above cursor, normal mode
map oo mmo<ESC>`m
map OO mmO<ESC>`m

"----- window navigation ---- 
nmap <c-j> <c-w>j
nmap <c-k> <c-w>k
nmap <c-l> <c-w>l
nmap <c-h> <c-w>h
" splits 
nmap <leader>v <C-w>v<C-w>l
nmap <leader>s <C-w>s<C-w>j

"---- File management (native vim) ----
nmap <leader>f :vsp! .<cr> " open file tree in left-vert-split
nmap <leader>hf :sp! .<cr> " file tree horizontal
nmap <leader>F :e! .<cr> " file tree in current buffer
nnoremap <leader>e <c-^> " switch between recent files

"---- invisible characters toggle ----
set invlist
set listchars=tab:▸\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
highlight SpecialKey ctermbg=none " make the highlighting of tabs less annoying
" set showbreak=↪
nmap <leader>p :set list!<cr>

"---- folding (thanks to Judd Vinet) ----
" Folding
"au BufNewFile,BufRead *              set foldmethod=manual
"au BufNewFile,BufRead *.c,*.h,*.php  set foldmethod=indent
"au BufNewFile,BufRead *.c,*.h,*.php  syn region myFold start="{" end="}" transparent fold
"au BufNewFile,BufRead *              set foldlevel=99

set foldmethod=manual
set foldlevel=99 " Don't fold anything by default - I'll close the folds myself
set foldminlines=5 " Don't bother folding small blocks

" Autoclose folds when moving out of them
"set foldclose=all

" Fold column
set foldcolumn=0

" ======= system ======
set clipboard=unnamed "  copy/paste

" indenting
set autoindent
set shiftwidth=2
set tabstop=2
set shiftround " set indent as multiple of shiftwidth

" ------ searching -----
set ignorecase
set smartcase

"----- checklists by me! ----- 
function! MakeCheckBox()
	:normal! mmI * [_] `m
endfunction

function! RemoveCheckBox()
	:normal! mm0rf*df] `m
endfunction

function! Check()
	:normal! mm0f_rx`m
endfunction

function! UnCheck()
	:normal! mm0fxr_`m
endfunction

nnoremap <leader>q :call MakeCheckBox()<cr>
nnoremap <leader>Q :call RemoveCheckBox()<cr>
nnoremap <leader>x :call Check()<cr>
nnoremap <leader>z :call UnCheck()<cr>

"====== display settings ======
syntax on
syntax enable


set wildmenu " enhanced command line completion
set hidden " current buffer can be put into background
set showcmd " show incomplete commands
set noshowmode " hides mode, use only if tmux will display mode instead, show incomplete commands
set laststatus=2 " display status line always
set wildmode=list:longest " complete files like a shell
set scrolloff=5 " lines of text around cursor
set shell=$SHELL
set cmdheight=1 " command bar height

set smartindent
set ruler " show cursor position always

set number
set relativenumber 
function! TogNum()
  set nu!
	set rnu
endfunction
function! TogRnu()
  set rnu!
	set nu
endfunction
autocmd FocusLost * call TogRnu()
autocmd FocusGained * call TogRnu()
autocmd InsertEnter * call TogRnu()
autocmd InsertLeave * call TogRnu()
" error bells
set noerrorbells
set visualbell
set t_vb=
set tm=500


"---- Text edit mode ----
function! TextMode ()
	setlocal formatoptions&vim
	set wrap " turn on line wrapping
	set wrapmargin=8 "wrap lines when coming within n characters from side
	set linebreak " set soft wrapping
	set showbreak=\~\~\  "show tildes at breaking
	set cursorline
	set so=7 " set 7 lines to the cursors - when moving vertical
	set complete&vim
	set formatprg&vim
	setlocal formatoptions&vim
endfunction
com! TM call TextMode()
nmap TM :TM<cr>

"---- Word Processor mode ----
" How do I set this to toggle??? 
func! WordProcessorMode()
	 "setlocal formatoptions=1
	 setlocal formatoptions=ant
	 setlocal textwidth=80
	 setlocal wrapmargin=0 "wrap lines when coming within n characters from side
	 setlocal noexpandtab
	 noremap j gj
	 noremap k gk
	 setlocal spell spelllang=en_us
"	set thesaurus+=~/.vim/thesaurus/mthesaur.txt
	 setlocal complete+=s
	 setlocal formatprg=par
	 setlocal wrap
	 setlocal linebreak
	 " --- indenting ---
	 " setlocal smartindent
			" or 
	 setlocal noautoindent
	 setlocal nocindent
	 setlocal nosmartindent
	 setlocal indentexpr=
	 setlocal nonumber 
	 setlocal nornu
endfu
com! WP call WordProcessorMode()

nmap WP :WP<cr>

"====== Plugins ======
"----- nerd tree ----
nmap <leader>t :NERDTreeToggle<cr>
let NERDTreeQuitOnOpen=1
let NERDTreeShowHidden=1

" ------ fugitive -----
nmap <silent> <leader>1 :Gstatus<cr>
nmap <leader>2 :Glog<cr>
nmap <leader>5 :Gcommit<cr>

" ------ airline ------
let g:airline_powerline_fonts=1
let g:airline_left_sep='❯'
set listchars=tab:▸\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
highlight SpecialKey ctermbg=none " make the highlighting of tabs less annoying
let g:airline_right_sep='❮'
let g:airline_theme='solarized'

"=================================
" ***  All system-wide defaults are set in $VIMRUNTIME/parabola.vim (usually just
" /usr/share/vim/vimfiles/parabola.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since parabola.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing parabola.vim since it alters the value of the
" 'compatible' option.
" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!
" This line should not be removed as it ensures that various options are " properly set to work with the Vim-related packages.
filetype plugin indent on
