" All system-wide defaults are set in $VIMRUNTIME/parabola.vim (usually just
" /usr/share/vim/vimfiles/parabola.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since parabola.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing parabola.vim since it alters the value of the
" 'compatible' option.
" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!
" This line should not be removed as it ensures that various options are " properly set to work with the Vim-related packages.
runtime! parabola.vim

" ----- plugin file source -----
source ~/.vim/plugins.vim
set nocompatible " use vim settings not vi 

" leader kery - comma
let mapleader = ','

"--------- rad Customizations-------

syntax on
syntax enable
set smartindent

" indenting
set autoindent
set shiftwidth=2
set tabstop=2
set shiftround " set indent as multiple of shiftwidth
" make indenting easier
nmap <leader>] >>
nmap <leader>[ <<

set cursorline
set ruler " show cursor position always

set number
set relativenumber ": Disabled for rita's og laptop
function! TogNum()
  set nu!
	set rnu
endfunction
function! TogRnu()
  set rnu!
	set nu
endfunction
autocmd FocusLost * call TogRnu()
autocmd FocusGained * call TogRnu()
autocmd InsertEnter * call TogRnu()
autocmd InsertLeave * call TogRnu()


"-------  Keybindings ----- 

" On honeysuckle:
" <esc> key mapped to <CapsLock> in X using this command: xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
" on  og laptop

" remap esc to comma-tab
inoremap <leader><tab> <esc>
		
		" inserts 2 blank lines below or above cursor, stay in normal mode
map oo 2o<ESC>2k
map OO 2O<ESC>2j

"  copy/paste
set clipboard=unnamed 

" save
nmap <leader><space> :w<cr>

"----- merd tree ----
nmap <leader>t :NERDTreeToggle<cr>
let NERDTreeQuitOnOpen=1
let NERDTreeShowHidden=1

" ------ fugitive -----
nmap <silent>
<leader>1 :Gstatus<cr>
nmap <leader>2 :Glog<cr>
nmap <leader>5 :Gcommit<cr>

" ------ airline ------
let g:airline_powerline_fonts=1
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_theme='solarized'

" ------ searching -----
set ignorecase
set smartcase

"------- borrowed configs ------
set so=7 " set 7 lines to the cursors - when moving vertical
set wildmenu " enhanced command line completion
set hidden " current buffer can be put into background
set showcmd " show incomplete commands
set noshowmode " show incomplete commands
set laststatus=2 " display status line always
set wildmode=list:longest " complete files like a shell
set scrolloff=5 " lines of text around cursor
set shell=$SHELL
set cmdheight=1 " command bar height

" error bells
set noerrorbells
set visualbell
set t_vb=
set tm=500

set wrap " turn on line wrapping
set wrapmargin=8 "wrap lines when coming within n characters from side
set linebreak " set soft wrapping
set showbreak=... "show ellipsis at breaking

"------- files --------
" switch between recent files
nnoremap <leader>e <c-^>
